debug: true

# 彩色日志
spring: 
  output: 
    ansi: 
      enabled: detect

# mysql
spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/qingdanxia?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    initialize: true
    druid: 
      max-active: 30
  jpa: 
    show-sql: true

# redis
spring: 
  redis: 
    database: 0
    host: 127.0.0.1
    port: 6379
    password: angelica
    timeout: 3000
    pool: 
      max-active: 1000
      max-wait: -1
      max-idle: 200
      min-idle: 2

